name: Create AWS Infra

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install pulumi pulumi-aws

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESSS_KEY}}
          aws-region: ap-southeast-1

      - name: Pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: pulumi login

      - name: Pulumi stack select
        run: |
          cd infra
          pulumi stack select shajalahamedcse/infra/aws-k3s

      - name: Pulumi refresh
        run: |
          cd infra
          pulumi refresh --yes

      - name: Set public key as github env
        run: echo "PUBLIC_KEY=${{ secrets.PUBLIC_KEY }}" >> $GITHUB_ENV

      - name: Pulumi up
        run: |
          cd infra
          pulumi up --yes 

      - name: Save Pulumi outputs
        id: pulumi_outputs
        run: |
          cd infra
          GIT_RUNNER_IP=$(pulumi stack output git_runner_public_ip)
          MASTER_IP=$(pulumi stack output master_private_ip)
          WORKER1_IP=$(pulumi stack output worker1_private_ip)
          WORKER2_IP=$(pulumi stack output worker2_private_ip)
          
          echo "GIT_RUNNER_IP=$GIT_RUNNER_IP" >> $GITHUB_ENV
          echo "MASTER_IP=$MASTER_IP" >> $GITHUB_ENV
          echo "WORKER1_IP=$WORKER1_IP" >> $GITHUB_ENV
          echo "WORKER2_IP=$WORKER2_IP" >> $GITHUB_ENV
