name: Setup GitHub Runner and Ansible

on:
  # workflow_run:
  #   workflows: ["Deploy Infrastructure"]
  #   types:
  #     - completed
  push:
    branches:
      - main
      - master

jobs:
  setup_runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESSS_KEY }}
          aws-region: ap-southeast-1
      
      - name: Pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: pulumi login

      - name: Pulumi stack select
        run: |
          cd infra
          pulumi stack select shajalahamedcse/infra/aws-k3s

      - name: Pulumi refresh
        run: |
          cd infra
          pulumi refresh --yes 
      
      - name: Save Pulumi outputs
        id: pulumi_outputs
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: |
          cd infra
          GIT_RUNNER_IP=$(pulumi stack output git_runner_public_ip)
          echo "GIT_RUNNER_IP=$GIT_RUNNER_IP" >> $GITHUB_ENV

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH to Runner EC2 and install GitHub Runner
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.GIT_RUNNER_IP }} << 'EOF'
          

